args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 1) {
  stop("Usage: Rscript r_scripts/Snapshot_Report.R <report_path>")
}

report_path <- args[[1]]

msg <- paste0(
  "Snapshot Report\n",
  "================\n",
  "Generated by R at ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\n",
  "R version: ", R.version.string, "\n"
)

cat("[R] Writing report to:", report_path, "\n")
dir.create(dirname(report_path), showWarnings = FALSE, recursive = TRUE)
writeLines(msg, con = report_path)
cat("[R] Report done.\n")
